### ISSUE TITLE
Montar en Simul8 los nuevos parámetros y comenzar a idear cómo modelar label TRIAJE

### ISSUE THREAD

**Issue by Teett** [Teett/systems_simulation#11]

**Comment by Teett** [comment]
Se integraron los nuevos parámetros con las distribuciones correctas. Baja prioridad: Falta ver qué ocurre con los tiempos entre llegadas ya que las distribuciones no ajustan bien.

**Comment by victorcatn** [comment]
hay que aplicar la exponencial a los parametros de la distribucion lognormal porque r bota el logaritmo

**Comment by victorcatn** [comment]
listo
