### ISSUE TITLE
Probar alternativas propuestas en el modelo y comentar los resultados

### ISSUE THREAD

**Issue by Teett** [Teett/systems_simulation#15]
Incluir análisis del costo de las alternativas (breve)

**Comment by andresquirogaleal** [comment]
ya se realizaron las tablas con los resultados de cada alternativa, tambien las tablas con los analisis de costos, por ultimo revisar y tomar decisiones.

**Comment by Teett** [comment]
Muy buen trabajo, las alternativas en la parte superior donde se proponen tienen numeración a, b, c y d. Por favor revisar para que coincida con la numeración 1, 2 y 3 realizada y cerramos issue. Ya corregí algunos temas de ortografía y orden. Si alguien sabe cómo hacer esas tablas más pequeñas se agradece.
