### ISSUE TITLE
Investigar si el tipo de triaje permite ajustar distribuciones separadas correctas a trauma y modelar en Simul8 con label para trauma.

### ISSUE THREAD

**Issue by Teett** [Teett/systems_simulation#4]

**Comment by victorcatn** [comment]
la separacion por triaje no mejora el ajuste de las distribuciones, lo que si ayudó fue cortar la cola descartando los tiempos de servicio mayores a 1 dia (antes el máximo eran 4 dias).
Con este nuevo supuesto, los datos ajustan lognormal:

Parameters:
         estimate Std. Error
meanlog 9.6381219 0.03807653
sdlog   0.7672207 0.02692396

**Comment by Teett** [comment]
Excelente, entonces el tema de los labels lo tratamos en el #11 juntos.

**Comment by Teett** [comment]
Victor la separación de probabilidad de triaje debe quedar documentada en el trabajo con el número de casos para cada tipo de triaje. en R lo hicimos ayer con `raw_data %>% count(nivelPrioridad)`
