### ISSUE TITLE
Realizar análisis descriptivo de las gráficas y comentar en los motivos de ocurrencia de los fenómenos

### ISSUE THREAD

**Issue by Teett** [Teett/systems_simulation#6]

**Comment by victorcatn** [comment]
usar este analisis para limpiar mejor los datos, eliminando los que no tengan sentido

**Comment by victorcatn** [comment]
la media de tiempo en consultorio adultos es demasiado alta (14 horas) lo que genera congestión en el modelo, se debe revisar por que ocurre esto

**Comment by Teett** [comment]
Se finalizó el análisis descriptivo en el informe final y se añadió un nuevo enfoque principal del modelo de simulación que indica que el propósito es generar escenarios prescriptivos que permitan tomar decisiones frente al COVID-19 dado un incremento en el número de llegadas a urgencias.
