### ISSUE TITLE
Crear las variables de desempeño faltantes de acuerdo a rúbrica en 1.5.

### ISSUE THREAD

**Issue by Teett** [Teett/systems_simulation#8]

**Comment by andresquirogaleal** [comment]
se crearon las 4 variables del tiempo promedio en cola, como tipo endogenas.
la monitora hace referencia a las variables de tamaño de las colas pero esas ya están en el trabajo, por lo tanto se omite ese procedimiento.

**Comment by Teett** [comment]
@andresquirogaleal bien importante que quede escrito en el trabajo la información de los tamaños promedio de las colas cuando estén las gráficas. No quedó incluido. Gracias.

**Comment by Teett** [comment]
Comentario anterior pertenece al issue #7, closed.
